"""empty message

Revision ID: 667e6a8bd567
Revises: bd1f075e1522
Create Date: 2018-06-30 12:35:17.322134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667e6a8bd567'
down_revision = 'bd1f075e1522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_article_old_20180615')
    op.add_column('article', sa.Column('thumbnail', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'thumbnail')
    op.create_table('_article_old_20180615',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.VARCHAR(length=500), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('descp', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
