"""empty message

Revision ID: a93a7fcda566
Revises: 667e6a8bd567
Create Date: 2018-07-23 18:00:03.017886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93a7fcda566'
down_revision = '667e6a8bd567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_article_old_20180703')
    op.drop_table('_article_old_20180703_1')
    op.add_column('article', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'likes')
    op.create_table('_article_old_20180703_1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.VARCHAR(length=5000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('descp', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=10), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_article_old_20180703',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('descp', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=10), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
