"""empty message

Revision ID: bd1f075e1522
Revises: 7aacb05e6bc0
Create Date: 2018-06-15 16:32:59.856552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1f075e1522'
down_revision = '7aacb05e6bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'category')
    # ### end Alembic commands ###
